ExceptionMessage: '実行できません'
StrangeVoice: 'キィエエェェェエエエエェェェッッッッッ!!!'
StrangeVoiceList:
  - 'ウンメエェエエエﾞエエエェェェエッ!!!!!'
  - 'ウメエエエェェェエェェェエエエッッ!!!!!!'
  - 'ウンメエエエエﾞエエエエエェェェエッ!!!!!!!'
  - 'ウメエエエェェェエェェェエエエッッッッッ!!!!!'
  - 'メエﾞエエﾞエェェエエﾞエﾞエﾞエェェェエﾞエェェッ!!!'
  - 'アンマアアァァァァアアアアァァアアァアアアアイッ!!!!!'
CatColor:
  - "RED"
  - "JELLIE"
  - "TABBY"
  - "BRITISH-SHORTHAIR"
  - "CALICO"
  - "PERSIAN"
  - "RAGDOLL"
  - "BLACK"
  - "SIAMESE"
flowers:
  - "DANDELION"
  - "POPPY"
  - "BLUE_ORCHID"
  - "ALLIUM"
  - "AZURE_BLUET"
  - "RED_TULIP"
  - "ORANGE_TULIP"
  - "WHITE_TULIP"
  - "PINK_TULIP"
  - "OXEYE_DAISY"
  - "CORNFLOWER"
  - "LILY_OF_THE_VALLEY"
  - "SUNFLOWER"
  - "LILAC"
  - "ROSE_BUSH"
  - "PEONY"
  - "TALL_GRASS"
mushrooms:
  - "BROWN_MUSHROOM"
  - "RED_MUSHROOM"
  - "CRIMSON_FUNGUS"
  - "WARPED_FUNGUS"