ExceptionMessage: '実行できません'
StrangeVoice: 'キィエエェェェエエエエェェェッッッッッ!!!'
StrangeVoiceList:
  - 'ウンメエェエエエﾞエエエェェェエッ!!!!!'
  - 'ウメエエエェェェエェェェエエエッッ!!!!!!'
  - 'ウンメエエエエﾞエエエエエェェェエッ!!!!!!!'
  - 'ウメエエエェェェエェェェエエエッッッッッ!!!!!'
  - 'メエﾞエエﾞエェェエエﾞエﾞエﾞエェェェエﾞエェェッ!!!'
  - 'アンマアアァァァァアアアアァァアアァアアアアイッ!!!!!'