ExceptionMessage: '実行できません'
StrangeVoice: 'キィエエェェェエエエエェェェッッッッッ!!!'
StrangeVoiceList:
  - 'ウンメエェエエエﾞエエエェェェエッ!!!!!'
  - 'ウメエエエェェェエェェェエエエッッ!!!!!!'
  - 'ウンメエエエエﾞエエエエエェェェエッ!!!!!!!'
  - 'ウメエエエェェェエェェェエエエッッッッッ!!!!!'
  - 'メエﾞエエﾞエェェエエﾞエﾞエﾞエェェェエﾞエェェッ!!!'
  - 'アンマアアァァァァアアアアァァアアァアアアアイッ!!!!!'
CatColor:
  - "RED"
  - "JELLIE"
  - "TABBY"
  - "BRITISH-SHORTHAIR"
  - "CALICO"
  - "PERSIAN",
  - "RAGDOLL"
  - "BLACK"
  - "SIAMESE"